### ISSUE TITLE
[BUG]: Baganator - Guild Bank

### ISSUE THREAD

**Issue by Aexxl** [jncl/Skinner#176] opened 2024-09-25 21:12 UTC
**WoW Version**
_Retail_

**AddOn skin name**
Baganator

**Describe the bug**
Opening the guild bank

```
1x Skinner/AddonSkins/Baganator.lua:262: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: in function `ipairs'
[string "@Skinner/AddonSkins/Baganator.lua"]:262: in function <Skinner/AddonSkins/Baganator.lua:250>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@Baganator/SingleViews/GuildView.lua"]:152: in function <Baganator/SingleViews/GuildView.lua:134>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"
```

**Comment by jncl** [comment] 2024-10-02 19:05
Hi,
Is this still an issue, I'm not able to reproduce it, or has it been fixed in the latest version?

**Comment by Aexxl** [comment] 2024-10-03 05:26
There was a similar error a couple off weeks ago (ticket #155)(opening the guild bank) that got fixed. 
Gettting the new error with version 11.56708.1

**Closed** 2024-10-05 22:49 UTC
Labels: bug
